MM03 Arbetsordning Omstrukturering
Datateknologerna-vid-Abo-Akademi/styrdocs pull request #1
Opened 2023-11-04 15:16 UTC by andreedd

Omstrukturering av "Tillsättande av kommittéer och arbetsgrupper" och "Funktionärer".
Eftersom enligt föreningens stadgar måste kommittéer och arbetsgrupper tillsätta en ordförande, måste vi kunna urskilja vilka de är i vår arbetsordning. 

Funktionärsstruktur exempel från KK arbetsordning.

Ändringarna:
* Omstrukturering
* Tilläggande/ändringar av antal

2023-11-04 15:18 UTC, andreedd commented
Se hela nya filen under: https://github.com/Datateknologerna-vid-Abo-Akademi/styrdocs/blob/4cd6a435acfa41c4f19a4c6264adbce3f66d3f9b/arbetsordning.md

2023-11-13 11:40 UTC, BenHaggl requested changes

2023-11-13 11:40 UTC, BenHaggl commented on arbetsordning.md
>  5. **Vice värdinna**
Formatering

2023-11-13 11:40 UTC, BenHaggl commented on arbetsordning.md
> +    Höstmötet tillsätter en Vice värdinna för följande verksamhetsår.
Höstmötet kan tillsätta en (1) Vice värdinna för följande verksamhetsår

2023-11-13 11:40 UTC, BenHaggl commented on arbetsordning.md
> +    En TiTeenitansvarig kan väljas under vårmötet.
Vårmötet kan tillsätta en (1) TiTeenitansvarig för följande verksamhetsår.

2023-11-13 14:38 UTC, merged