MM03 Stadgar ändringsförslag
Datateknologerna-vid-Abo-Akademi/styrdocs pull request #19
Opened 2024-10-26 10:53 UTC by Alexdunderdander

Ändringar:
- Lade till Icke-fullständig medlem
- Lade till Utbytesmedlem

- Fixade formulering paragraf 25

2024-10-28 11:29 UTC, andreedd commented on stadgar.md
> +**§ 8 Hedersmedlemmar**
DRY=Don’t Repeat Yourself

Istället för att definiera nya medlemstyper med exakt samma rättigheter som gulnäbbsmedlemmar, skulle det gå att tillägga vem som kan bli gulnäbsmedlemmar. Blir även mindre råddigt att ha väldigt många medlemstyper.

Ex.  ändra gulnäbbsmedlemmarnas definition från:
"Till gulnäbbsmedlemmar kan antas första årets teknik- eller kemistuderande vid Åbo Akademi."
Till något i stil med:

"Till gulnäbbsmedlemmar kan antas första årets teknik- eller kemistuderande vid Åbo Akademi, tidigare gulnäbbsmedlemmar som inte uppfyllt ordinariemedlemskraven, samt utbytesstuderanden vid Åbo Akademi inom ämnet informationsteknologi."

Då skulle vi inte behöva tillägga de här medlemstyperna alls, och de personerna de är ämnade för skulle ha samma rättigheter som förslagen.

2024-10-28 12:00 UTC, andreedd commented
Egen åsikt om medlemstyper:

Studerar du Datateknik på ÅA -> Gulnäbbsmedlem
Studerar du Datateknik på ÅA och har avlagt medlemskraven -> Ordinariemedlem
Studerar inte  Datateknik på ÅA och inte heller varit ordinariemedlem -> Stödjandemedlem
Slutfört studier och har varit ordinariemedlem -> Seniormedlem
Jättekivatyp som ha gjort myki för DaTe länge -> Hedersmedlem

Tror nog int att vi ska behöva så mycket mera medlemstyper än de här, om man definierar dom väl 🤔  (t.ex. vad vi definierat så KKare kan bli medlemmar)

2024-11-04 10:30 UTC, andreedd commented
@Alexdunderdander Kommentar gällande att stadgarna inte ska innehålla rättigheter för utbytesstuderanden att anta förtroendeuppdrag:

* Om nu nån utbytesstuderande på riktigt kommer på möte, vill ställa upp, och mötet anser att personen är passande och ska bli vald till posten, så är det högst antagligen vettigt att kunna få välja personen för uppdraget. Fast stadgarna tillåter dem att anta förtroendeuppdrag, betyder det inte att de lätt blir valda till dem.

2024-11-04 19:43 UTC, jaspnas approved these changes, later dismissed

2024-11-13 15:22 UTC, andreedd requested changes

2024-11-13 15:22 UTC, andreedd commented on stadgar.md
> +(ändrade och godkändes på föreningens höstmöte 13.11.2024)
Ska vara "justerade"

2024-11-13 15:23 UTC, andreedd commented on stadgar.md
> +(ändrade och godkändes på föreningens höstmöte 13.11.2024)
Skål möte! 
[![image](https://github.com/user-attachments/assets/4e87b15a-c428-455d-8aab-2a1dc0dfa8a0)]()

2024-11-13 15:25 UTC, Alexdunderdander commented on stadgar.md
> +(ändrade och godkändes på föreningens höstmöte 13.11.2024)
vi justerade dock int rikti någå idag, vi godkänd ju bara de. Ska de ändå stå justerades?

2024-11-13 15:28 UTC, andreedd commented on stadgar.md
> +(ändrade och godkändes på föreningens höstmöte 13.11.2024)
Dehär e de som skickas åt prh, de e final efter att de ha godkänts av möte efter 2 ggr fast de int ha skickats åt prh 😀

2025-02-10 10:55 UTC, idikiwibri approved these changes

2025-02-10 10:57 UTC, merged